name: aws_tgw_direct_exp_teardown
# label used for menu selection
label: AWS Transit Gateway Firewalls Step 3 Teardown

description: >
  This skillet will destroy the cloudformation stack.
  The skillet will destroy the bootstrap folders in S3.
  Run this step once the demo is complete.
  
  
  Stack deletion will normall take approximately 15 minutes. 

# type of skillet (panos or panorama or template or terraform)
type: python3

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  cft: aws
  collection:
    - AWS TGW
    - Deploy
    - Public Cloud
    - Template

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: aws_access_key
    description: AWS Access Key
    default: abc123
    type_hint: text
  - name: aws_secret_key
    description: AWS Secret Key
    default:
    type_hint: password


# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: script
    file: ../../destroy.py
#    output_type:
#    outputs:
#      - name: app_threat_version
#        capture_pattern: result/content-updates/entry/version
